//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget_v4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payday
    {
        public long Id { get; set; }
        public System.DateTime Day { get; set; }
        public decimal Value { get; set; }
        public long UserId { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
