//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Budget_v4.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Savings
    {
        public string Id { get; set; }
        public Nullable<decimal> Value { get; set; }
    }
}
